pipeline {
    agent any
    environment {
        REPORT_PATH = '**/target/scala-0.24/dependency-check-report.xml'
    }
    stages {
        stage('Compile') {
            steps {
                dir('dotty-example-project'){
                    sh 'sbt clean compile'
                }
            }
            post{
                success{
                    echo 'Compile done'
                    sh 'rm -rf dotty-example-project/target/scala-0.24/dependency-check-report.xml'
                }
            }
        }
        stage('Dependencies Check') {
            steps {
                dir('dotty-example-project'){
                    sh 'sbt dependencyCheck'
                    archiveArtifacts artifacts: "${REPORT_PATH}", fingerprint: true, onlyIfSuccessful: true
                    //dependencyCheckPublisher pattern: '**/tarjet/scala-0.24/dependency-check-report.xml'
                }
            }
            post{
                unstable{
                    echo 'Could not publish the report'
                }
            }
        }
        stage('Analysis Of Dependency Check Report') {
            steps {
                dir('dotty-example-project/utils'){
                    sh 'npm install'
                    sh 'npm test'
                }
            }
            post{
                failure{
                    script {
                        currentBuild.result = 'UNSTABLE'
                        currentBuild.description = 'Vulnerabilities detected'
                    }
                }
            }
        }
    }
}
