pipeline {
    agent any
    environment {
        PROJECT_PATH = 'dotty-example-project'
        REPORT_PATH = "${env.WORKSPACE}/${PROJECT_PATH}/reports/dependency-check-report.xml"
    }
    stages {
        stage('Compile') {
            steps {
                dir("${PROJECT_PATH}"){
                    sh 'sbt clean compile'
                }
            }
        }
        stage('Dependencies Check') {
            steps {
                dir("${PROJECT_PATH}"){
                    sh 'sbt dependencyCheck'
                    dependencyCheckPublisher pattern: "/reports/dependency-check-report.xml"
                }
            }
            post{
                unstable{
                    echo 'Could not publish the report'
                }
            }
        }
        stage('Analysis Of Dependency Check Report') {
            steps {
                dir("${PROJECT_PATH}/utils"){
                    sh 'npm install'
                    script{
                        def returnValue = sh(
                            returnStatus: true,
                            script: '''
                                npm test
                            '''
                        )
                        if(returnValue != 0) {
                            currentBuild.result = 'UNSTABLE';
                            currentBuild.description = "Vulnerabilities detected";
                       }
                    }
                }
            }
        }
    }
}
